name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get environment
      run: vars
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Pscheme=${{secrets.API_SCHEME}} -Phost=${{secrets.API_HOST}} -PjsonPath=${{secrets.API_PATH_JSON}} -PassetsPath=${{secrets.API_PATH_ASSETS}}
