name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: >-
          ./gradlew build 
          -PpropScheme=${{secrets.API_SCHEME}} 
          -PpropHost=${{secrets.API_HOST}} 
          -PpropJsonPath=${{secrets.API_PATH_JSON}} 
          -PpropAssetsPath=${{secrets.API_PATH_ASSETS}} 
          -PpropKeystoreFile=${{secrets.KEYSTORE_FILE}}
          -PpropKeystorePassword=${{secrets.KEYSTORE_PASSWORD}}
          -PpropKeystoreKey=${{secrets.KEYSTORE_KEY}}
          -PpropKeyPassword=${{secrets.KEY_PASSWORD}}
